apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: pika3kw/post-service
